/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJPanel.java
 *
 * Created on 25/07/2011, 17:33:14
 */
package configuraGrid;

/**
 *
 * @author hayato
 */
public class Prototipo extends javax.swing.JPanel {

    /** Creates new form NewJPanel */
    public Prototipo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaChat = new javax.swing.JTextArea();
        botEnviar = new javax.swing.JButton();
        areaEntrada = new javax.swing.JTextField();
        botDesconectar = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        areaChat.setColumns(20);
        areaChat.setEditable(false);
        areaChat.setFont(areaChat.getFont());
        areaChat.setLineWrap(true);
        areaChat.setRows(5);
        areaChat.setAutoscrolls(false);
        areaChat.setBorder(null);
        areaChat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(areaChat);

        botEnviar.setText("Enviar");
        botEnviar.setMaximumSize(new java.awt.Dimension(95, 23));
        botEnviar.setMinimumSize(new java.awt.Dimension(95, 23));
        botEnviar.setPreferredSize(new java.awt.Dimension(95, 23));
        botEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEnviarActionPerformed(evt);
            }
        });

        botDesconectar.setText("Desconectar");
        botDesconectar.setToolTipText("Desconectar e desistir do jogo.");
        botDesconectar.setMaximumSize(new java.awt.Dimension(95, 23));
        botDesconectar.setMinimumSize(new java.awt.Dimension(95, 23));
        botDesconectar.setPreferredSize(new java.awt.Dimension(95, 23));
        botDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDesconectarActionPerformed(evt);
            }
        });

        labelNome.setText("Nome");
        labelNome.setMaximumSize(new java.awt.Dimension(70, 14));
        labelNome.setMinimumSize(new java.awt.Dimension(70, 14));
        labelNome.setPreferredSize(new java.awt.Dimension(70, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(areaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(botDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(465, 465, 465)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEnviarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_botEnviarActionPerformed

    private void botDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDesconectarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_botDesconectarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaChat;
    private javax.swing.JTextField areaEntrada;
    private javax.swing.JButton botDesconectar;
    private javax.swing.JButton botEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNome;
    // End of variables declaration//GEN-END:variables
}
