/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProtoChat.java
 *
 * Created on 26/07/2011, 01:25:48
 */
package componentesUI;

/**
 *
 * @author hayato
 */
public class ProtoChat extends javax.swing.JPanel {

    /** Creates new form ProtoChat */
    public ProtoChat() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaChat = new javax.swing.JTextArea();
        labelNome = new javax.swing.JLabel();
        areaEntrada = new javax.swing.JTextField();
        botEnviar = new javax.swing.JButton();

        areaChat.setColumns(20);
        areaChat.setEditable(false);
        areaChat.setFont(areaChat.getFont());
        areaChat.setLineWrap(true);
        areaChat.setRows(5);
        areaChat.setAutoscrolls(false);
        areaChat.setBorder(null);
        areaChat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(areaChat);

        labelNome.setText("Nome");
        labelNome.setMaximumSize(new java.awt.Dimension(70, 14));
        labelNome.setMinimumSize(new java.awt.Dimension(70, 14));
        labelNome.setPreferredSize(new java.awt.Dimension(70, 14));

        botEnviar.setText("Enviar");
        botEnviar.setMaximumSize(new java.awt.Dimension(95, 23));
        botEnviar.setMinimumSize(new java.awt.Dimension(95, 23));
        botEnviar.setPreferredSize(new java.awt.Dimension(95, 23));
        botEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEnviarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_botEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaChat;
    private javax.swing.JTextField areaEntrada;
    private javax.swing.JButton botEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNome;
    // End of variables declaration//GEN-END:variables
}
